reads: ['R1', 'R2']
sample: "{biorep}_{condition}"
genome_size: 2506966135
effective_size: 2365156725
ref: "/home/pengsc/reference/refgenie/equcab3/alias/equcab3/fasta/default/equcab3.fa"
ref_idx: "/home/pengsc/reference/refgenie/equcab3/alias/equcab3/bwa_index/default/equcab3.fa"
chrom_sizes: "/home/pengsc/reference/refgenie/equcab3/alias/equcab3/fasta/default/equcab3.chrom.sizes"
gff: "/home/pengsc/projects/Iso-seq/snakemake_pipeline/Results/Merged/faang.ref.combined.annotated.gtf"
#gff: "/home/pengsc/reference/equcab3/RefSeq/AnnotationRelease103/GCF_002863925.1_EquCab3.0_genomic.renamed.gff"
