name: atac_snakemake

pep_version: 2.0.0
sample_table: sample_table.csv

output_dir: "../results"

sample_modifiers:
  append:
    input_dir: "resources/raw_reads"
  derive:
    attributes: [read1, read2, sample_name]
    sources:
      SAMPLE_NAME: "{bio_sample}_{condition}"
      FQ1: "{input_dir}/{bio_sample}_{condition}_R1.fastq.gz"
      FQ2: "{input_dir}/{bio_sample}_{condition}_R2.fastq.gz"
      
project_modifiers:
  amend:
    test_workflow:
      sample_table: test_sample_table.csv
      output_dir: "../test_results"
      sample_modifiers:
        append:
          input_dir: "resources/test_reads"